// AI Nexus Academy - Full-Stack Local Server & REST API Engine
const http = require('http');
const fs = require('fs');
const path = require('path');

const PORT = process.env.PORT || 3000;
const MIME_TYPES = {
  '.html': 'text/html',
  '.css': 'text/css',
  '.js': 'text/javascript',
  '.json': 'application/json',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.svg': 'image/svg+xml',
  '.ico': 'image/x-icon',
  '.txt': 'text/plain'
};

// Helper: parse JSON request body
function parseRequestBody(req) {
  return new Promise((resolve, reject) => {
    let body = '';
    req.on('data', chunk => {
      body += chunk.toString();
      // Safeguard against large payloads
      if (body.length > 1e6) {
        req.destroy();
        reject(new Error('Payload too large'));
      }
    });
    req.on('end', () => {
      if (!body) {
        resolve({});
        return;
      }
      try {
        resolve(JSON.parse(body));
      } catch (err) {
        resolve({ raw: body });
      }
    });
    req.on('error', reject);
  });
}

// Helper: Send JSON response with CORS & Security Headers
function sendJsonResponse(res, statusCode, data) {
  res.writeHead(statusCode, {
    'Content-Type': 'application/json; charset=utf-8',
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type, Authorization, X-Requested-With',
    'X-Content-Type-Options': 'nosniff',
    'X-Frame-Options': 'SAMEORIGIN',
    'X-XSS-Protection': '1; mode=block',
    'Referrer-Policy': 'strict-origin-when-cross-origin',
    'Cache-Control': 'no-cache'
  });
  res.end(JSON.stringify(data, null, 2));
}

// Mock AI / Knowledge Data for API
const API_COURSES = [
  { id: 'ai-101', title: 'Vibe Coding & AI App Development', tier: 'Low Tier', price: 1500, weeks: 4 },
  { id: 'ai-201', title: 'Cloud Hosting & Software Integration', tier: 'Mid Tier', price: 2500, weeks: 8 },
  { id: 'ai-301', title: 'API Architecture & AI Engine APIs', tier: 'High Tier', price: 3500, weeks: 10 },
  { id: 'ai-401', title: 'Advanced AI Architecture & MLOps', tier: 'Highest Tier', price: 5000, weeks: 14 }
];

const server = http.createServer(async (req, res) => {
  const parsedUrl = new URL(req.url, `http://${req.headers.host}`);
  const pathname = parsedUrl.pathname;
  const method = req.method.toUpperCase();

  // Handle CORS Preflight OPTIONS
  if (method === 'OPTIONS') {
    res.writeHead(204, {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS',
      'Access-Control-Allow-Headers': 'Content-Type, Authorization, X-Requested-With'
    });
    res.end();
    return;
  }

  // =========================================================================
  // REST API ROUTING (/api/v1/...)
  // =========================================================================
  if (pathname.startsWith('/api/')) {
    const startTime = Date.now();

    try {
      // 1. Health & Telemetry
      if (pathname === '/api/v1/health' && method === 'GET') {
        return sendJsonResponse(res, 200, {
          status: 'ONLINE',
          service: 'AI Nexus Academy Engine API',
          version: 'v4.2.0',
          gpuNodes: '8x NVIDIA H100 SXM5 Online',
          uptime: process.uptime(),
          timestamp: new Date().toISOString(),
          latencyMs: Date.now() - startTime
        });
      }

      // 2. Courses Catalog API
      if (pathname === '/api/v1/courses' && method === 'GET') {
        return sendJsonResponse(res, 200, {
          success: true,
          count: API_COURSES.length,
          data: API_COURSES,
          timestamp: new Date().toISOString()
        });
      }

      // 3. Vibe Coding Prompt Generator API
      if (pathname === '/api/v1/vibe/generate' && method === 'POST') {
        const body = await parseRequestBody(req);
        const appType = body.appType || 'saas_analytics';
        const frontend = body.frontend || 'react_tailwind';
        const backend = body.backend || 'supabase';
        const style = body.style || 'glassmorphism';

        const masterPrompt = `### PROJECT SPECIFICATION (GENERATED BY NEXUS API)
Build a production-ready "${appType.replace(/_/g, ' ').toUpperCase()}" application.

### TECH STACK
- Frontend: ${frontend}
- Backend / DB: ${backend}
- Aesthetic Theme: ${style}

### REQUIREMENTS
1. Fully responsive layouts with keyboard accessibility.
2. Complete CRUD state management with instant optimistic UI.
3. Robust error boundaries, empty states, and toast feedback.`;

        const fileTree = [
          `.cursorrules`,
          `package.json`,
          `src/App.tsx`,
          `src/components/Navbar.tsx`,
          `src/components/MainView.tsx`,
          `src/lib/client.ts`
        ];

        return sendJsonResponse(res, 200, {
          success: true,
          meta: { appType, frontend, backend, style },
          masterPrompt,
          fileTree,
          rulesConfig: `# .cursorrules\nTechStack: ${frontend} + ${backend}\nRules: Modular architecture, zero placeholder ellipses, full typing.`,
          latencyMs: Date.now() - startTime
        });
      }

      // 4. Prompt Optimizer API
      if (pathname === '/api/v1/prompt/optimize' && method === 'POST') {
        const body = await parseRequestBody(req);
        const rawPrompt = body.prompt || '';
        const domain = body.domain || 'coding';

        if (!rawPrompt.trim()) {
          return sendJsonResponse(res, 400, {
            error: 'Missing required field: "prompt"'
          });
        }

        const optimizedPrompt = `### ROLE & ENVIRONMENT
Act as an elite Senior Specialist in ${domain.toUpperCase()}.

### CONTEXT & GOAL
${rawPrompt}

### CONSTRAINTS & ACCEPTANCE CRITERIA
1. Provide production-grade, modular, self-documenting implementation.
2. Include edge-case test suites and validation handling.
3. Adhere to crisp formatting with zero placeholder ellipses.`;

        return sendJsonResponse(res, 200, {
          success: true,
          domain,
          rawLength: rawPrompt.length,
          qualityScore: 98,
          optimizedPrompt,
          improvements: [
            'Added explicit role and persona anchor.',
            'Enforced negative constraints against hallucinations.',
            'Added unit test and error boundary requirements.'
          ],
          latencyMs: Date.now() - startTime
        });
      }

      // 5. Tokenizer API
      if (pathname === '/api/v1/tokens/tokenize' && method === 'POST') {
        const body = await parseRequestBody(req);
        const text = body.text || 'AI Nexus Academy';
        const words = text.match(/[\w]+|[^\w\s]|\s+/g) || [];
        const tokens = [];

        words.forEach(w => {
          if (w.length > 5 && !w.includes(' ')) {
            tokens.push({ text: w.slice(0, 3), id: (w.charCodeAt(0) * 137) % 99999 });
            tokens.push({ text: w.slice(3), id: (w.charCodeAt(1) * 251) % 99999 });
          } else {
            tokens.push({ text: w, id: (w.charCodeAt(0) * 181) % 99999 });
          }
        });

        return sendJsonResponse(res, 200, {
          success: true,
          text,
          characterCount: text.length,
          tokenCount: tokens.length,
          tokens,
          estimatedCostUsd: (tokens.length / 1000000) * 2.50,
          latencyMs: Date.now() - startTime
        });
      }

      // 6. Vector RAG Simulation API
      if (pathname === '/api/v1/rag/simulate' && method === 'POST') {
        const body = await parseRequestBody(req);
        const query = body.query || 'What GPUs does AI-401 run on?';

        return sendJsonResponse(res, 200, {
          success: true,
          query,
          embeddingModel: 'text-embedding-3-small',
          vectorDimension: 1536,
          matches: [
            {
              docId: 'DOC-9482',
              chunkId: 'CHUNK-01',
              text: 'AI Nexus Model AI-401 runs on 8x H100 GPUs with 3.2TB/s memory bandwidth.',
              cosineSimilarity: 0.942
            },
            {
              docId: 'DOC-9482',
              chunkId: 'CHUNK-02',
              text: 'NVIDIA H100 SXM5 GPU nodes feature 80GB HBM3 memory per accelerator.',
              cosineSimilarity: 0.887
            }
          ],
          groundedAnswer: 'AI-401 utilizes 8x NVIDIA H100 SXM5 GPUs with 3.2TB/s memory bandwidth (Source: DOC-9482).',
          hallucinationRisk: '0.00%',
          latencyMs: Date.now() - startTime
        });
      }

      // 7. Study Tutor Explainer API
      if (pathname === '/api/v1/tutor/explain' && method === 'POST') {
        const body = await parseRequestBody(req);
        const topic = body.topic || 'llm_basics';
        const mode = body.mode || 'eli5';

        const explanations = {
          eli5: 'Think of an LLM as a giant predictive text machine that has read billions of books. It guesses the next puzzle piece word over and over.',
          practical: 'Use LLMs to draft emails, summarize 50-page PDFs into 5 bullets, write Python code, or structure customer support responses.',
          technical: 'Autoregressive Transformer decoder networks optimizing categorical cross-entropy loss over subword vocabulary logits with temperature sampling.'
        };

        return sendJsonResponse(res, 200, {
          success: true,
          topic,
          mode,
          explanation: explanations[mode] || explanations.eli5,
          latencyMs: Date.now() - startTime
        });
      }

      // 8. AI Security & Guardrail Audit API
      if (pathname === '/api/v1/security/audit' && method === 'POST') {
        const body = await parseRequestBody(req);
        const target = body.codeOrPrompt || 'Select * from users where role = "admin"';
        const scanType = body.scanType || 'all';

        const issues = [];
        if (target.toLowerCase().includes('password') || target.toLowerCase().includes('secret') || target.toLowerCase().includes('sk-')) {
          issues.push({ severity: 'CRITICAL', title: 'Hardcoded Secret Detected', description: 'API Key or plain text password found in payload. Move to environment variables.' });
        }
        if (target.toLowerCase().includes('ignore previous instructions') || target.toLowerCase().includes('system prompt')) {
          issues.push({ severity: 'HIGH', title: 'Prompt Injection Risk', description: 'Detected attempt to override system instructions or bypass guardrails.' });
        }
        if (target.toLowerCase().includes('select *') || target.toLowerCase().includes('drop table')) {
          issues.push({ severity: 'MEDIUM', title: 'Unparameterized SQL Risk', description: 'Raw SQL detected without prepared statements. Use ORM or parameterized queries.' });
        }

        const safetyScore = issues.length === 0 ? 100 : Math.max(40, 100 - (issues.length * 25));

        return sendJsonResponse(res, 200, {
          success: true,
          scanType,
          safetyScore,
          status: safetyScore > 80 ? 'PASSED_GUARDRAILS' : 'ATTENTION_REQUIRED',
          issuesCount: issues.length,
          issues: issues.length > 0 ? issues : [{ severity: 'LOW', title: 'Zero High-Risk Vulnerabilities', description: 'Code passed OWASP Top 10 for LLMs and input validation.' }],
          recommendedHardening: [
            'Wrap user inputs with strict Zod/Pydantic schemas.',
            'Apply system delimiters (### SYSTEM) to isolate user prompt vectors.',
            'Enforce Row Level Security (RLS) on backend database queries.'
          ],
          latencyMs: Date.now() - startTime
        });
      }

      // 9. Frontend Component Generator API
      if (pathname === '/api/v1/frontend/component' && method === 'POST') {
        const body = await parseRequestBody(req);
        const componentType = body.componentType || 'dashboard_metric_card';
        const theme = body.theme || 'glassmorphism_light';

        const codeSnippet = `import React, { useState } from 'react';
import { Sparkles, TrendingUp, ShieldCheck } from 'lucide-react';

export const NexusMetricCard = ({ title = "Active AI Agents", value = "1,420", trend = "+24.5%" }) => {
  const [hovered, setHovered] = useState(false);

  return (
    <div 
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
      className="relative p-6 rounded-2xl bg-white/90 backdrop-blur-xl border border-slate-200/80 shadow-lg hover:shadow-cyan-500/10 hover:-translate-y-1 transition-all duration-300 overflow-hidden"
    >
      <div className="flex justify-between items-start mb-3">
        <span className="text-xs font-extrabold uppercase tracking-wider text-slate-500">{title}</span>
        <span className="p-2 rounded-xl bg-cyan-50 text-cyan-600"><Sparkles size={16} /></span>
      </div>
      <div className="text-3xl font-black text-slate-900 tracking-tight">{value}</div>
      <div className="flex items-center gap-1.5 mt-3 text-xs font-bold text-emerald-600">
        <TrendingUp size={14} /> <span>{trend} vs last cycle</span>
      </div>
    </div>
  );
};`;

        return sendJsonResponse(res, 200, {
          success: true,
          componentType,
          framework: 'React 19 + Tailwind CSS + Lucide Icons',
          theme,
          codeSnippet,
          features: ['Glassmorphic backdrop blur', 'Interactive hover physics', '100% accessible contrast ratio', 'Zero external runtime bloat'],
          latencyMs: Date.now() - startTime
        });
      }

      // 10. Backend Microservice Architecture API
      if (pathname === '/api/v1/backend/microservice' && method === 'POST') {
        const body = await parseRequestBody(req);
        const service = body.service || 'fastapi_agent_worker';

        const pythonCode = `from fastapi import FastAPI, Depends, HTTPException, status
from pydantic import BaseModel, Field
from fastapi.middleware.cors import CORSMiddleware
import time

app = FastAPI(title="Nexus AI Agent Gateway", version="1.0.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

class AgentTaskRequest(BaseModel):
    task_id: str = Field(..., example="task_rag_901")
    prompt: str = Field(..., min_length=5, max_length=4000)
    temperature: float = Field(0.2, ge=0.0, le=1.5)

@app.post("/api/v1/agent/execute", status_code=status.HTTP_200_OK)
async def execute_agent(payload: AgentTaskRequest):
    start = time.time()
    # Execute sandboxed reasoning loop
    result = {
        "task_id": payload.task_id,
        "status": "COMPLETED",
        "tokens_processed": len(payload.prompt) // 4,
        "execution_time_ms": round((time.time() - start) * 1000, 2)
    }
    return result`;

        return sendJsonResponse(res, 200, {
          success: true,
          service,
          architecture: 'FastAPI + Pydantic Schema Validation + Async Event Loop',
          codeSnippet: pythonCode,
          recommendedStack: ['FastAPI (Python 3.12)', 'Uvicorn ASGI', 'Redis Token Bucket Rate Limiter', 'PostgreSQL with pgvector'],
          latencyMs: Date.now() - startTime
        });
      }

      // 11. UI/UX Design System & Token Generator API
      if (pathname === '/api/v1/uiux/wireframe' && method === 'POST') {
        const body = await parseRequestBody(req);
        const screenType = body.screenType || 'ai_saas_dashboard';

        return sendJsonResponse(res, 200, {
          success: true,
          screenType,
          designSystem: {
            colorTokens: {
              primary: '#0284c7 (Sky Cyan)',
              secondary: '#7c3aed (Violet Accent)',
              background: '#f8fafc (Light Slate Canvas)',
              surface: 'rgba(255, 255, 255, 0.92) Glass',
              textPrimary: '#0f172a (High Contrast Slate 900)',
              textSecondary: '#64748b (Slate 500)'
            },
            typography: {
              headingFont: 'Outfit, -apple-system, sans-serif',
              bodyFont: 'Inter, -apple-system, sans-serif',
              codeFont: 'JetBrains Mono, monospace'
            },
            spacingScale: ['4px', '8px', '16px', '24px', '32px', '48px'],
            elevationShadows: {
              sm: '0 2px 8px rgba(0,0,0,0.04)',
              md: '0 10px 30px rgba(15,23,42,0.08)',
              glow: '0 0 25px rgba(2,132,199,0.2)'
            }
          },
          uxBestPractices: [
            'Stream response tokens incrementally via SSE to minimize perceived time to first token (TTFT < 300ms).',
            'Include micro-interactions & audio feedback chimes on reward unlock.',
            'Display explicit status badges and latency telemetry so users stay informed.'
          ],
          latencyMs: Date.now() - startTime
        });
      }

      // 12. Frontier AI Model Arena Benchmark API
      if (pathname === '/api/v1/arena/compare' && method === 'POST') {
        const body = await parseRequestBody(req);
        const prompt = body.prompt || 'Write a concurrent Web Crawler in Go with rate limiting.';
        const modelA = body.modelA || 'claude-3-7-sonnet';
        const modelB = body.modelB || 'gpt-o3-mini';

        const modelKnowledge = {
          'claude-3-7-sonnet': {
            name: 'Claude 3.7 Sonnet',
            provider: 'Anthropic',
            tokensPerSec: 88,
            inputCostPer1M: '$3.00',
            outputCostPer1M: '$15.00',
            reasoningTrace: `[THINKING PROCESS]
1. Analyzing user prompt requirements: concurrency, worker pool pattern, rate limiting.
2. Architecture choice: Go goroutines + buffered channels + sync.WaitGroup + context.Context cancellation.
3. Rate limiting strategy: time.Ticker or golang.org/x/time/rate token bucket.
4. Constructing clean, error-handled production implementation.`,
            output: `\`\`\`go
package main

import (
    "context"
    "fmt"
    "net/http"
    "sync"
    "time"
)

type Crawler struct {
    client   *http.Client
    limiter  <-chan time.Time
    wg       sync.WaitGroup
    visited  sync.Map
}

func NewCrawler(rateLimit time.Duration) *Crawler {
    return &Crawler{
        client:  &http.Client{Timeout: 5 * time.Second},
        limiter: time.Tick(rateLimit),
    }
}

func (c *Crawler) Crawl(ctx context.Context, url string, depth int) {
    if depth <= 0 { return }
    if _, loaded := c.visited.LoadOrStore(url, true); loaded { return }

    <-c.limiter // Enforce token rate limit
    c.wg.Add(1)
    go func() {
        defer c.wg.Done()
        req, _ := http.NewRequestWithContext(ctx, "GET", url, nil)
        resp, err := c.client.Do(req)
        if err != nil { fmt.Printf("Error: %v\\n", err); return }
        defer resp.Body.Close()
        fmt.Printf("Crawled: %s [Status: %d]\\n", url, resp.StatusCode)
    }()
}
\`\`\``
          },
          'gpt-o3-mini': {
            name: 'OpenAI o3-mini',
            provider: 'OpenAI',
            tokensPerSec: 64,
            inputCostPer1M: '$1.10',
            outputCostPer1M: '$4.40',
            reasoningTrace: `[O3-MINI REASONING]
- Goal: Implement concurrent crawler with rate-limiting in Go.
- Constraints: Thread safety with visited URL set, bounded concurrency.
- Solution: Buffered channel worker pool + sync.Mutex protected map.`,
            output: `\`\`\`go
package main

import (
    "fmt"
    "sync"
    "time"
)

func worker(id int, jobs <-chan string, wg *sync.WaitGroup, rateLimit <-chan time.Time) {
    defer wg.Done()
    for url := range jobs {
        <-rateLimit
        fmt.Printf("Worker %d fetching: %s\\n", id, url)
        // Perform HTTP GET request here
    }
}

func main() {
    urls := []string{"https://golang.org", "https://ainexus.edu", "https://pkg.go.dev"}
    jobs := make(chan string, len(urls))
    var wg sync.WaitGroup
    limiter := time.Tick(200 * time.Millisecond)

    for w := 1; w <= 3; w++ {
        wg.Add(1)
        go worker(w, jobs, &wg, limiter)
    }
    for _, u := range urls { jobs <- u }
    close(jobs)
    wg.Wait()
}
\`\`\``
          },
          'deepseek-r1': {
            name: 'DeepSeek R1 (671B)',
            provider: 'DeepSeek AI',
            tokensPerSec: 42,
            inputCostPer1M: '$0.55',
            outputCostPer1M: '$2.19',
            reasoningTrace: `[CHAIN-OF-THOUGHT REASONING]
Let's consider the problem systematically. In Go, concurrent web crawling requires:
1. Deduplication using sync.Map to avoid redundant crawls and infinite loops.
2. Semaphore/Worker channel pattern to avoid exhausting socket descriptors (ulimit).
3. Rate limiting using a channel ticker or token bucket algorithm.`,
            output: `\`\`\`go
// DeepSeek-R1 Architecture: Semaphore Concurrency Pattern
package main

import (
    "context"
    "fmt"
    "sync"
    "golang.org/x/time/rate"
)

type SafeCrawler struct {
    limiter *rate.Limiter
    sem     chan struct{} // Concurrency throttle
    visited sync.Map
}

func (s *SafeCrawler) Fetch(ctx context.Context, target string) {
    if err := s.limiter.Wait(ctx); err != nil { return }
    s.sem <- struct{}{}        // Acquire token
    defer func() { <-s.sem }() // Release token
    fmt.Println("Crawling:", target)
}
\`\`\``
          },
          'gemini-2-0-flash': {
            name: 'Gemini 2.0 Flash',
            provider: 'Google DeepMind',
            tokensPerSec: 135,
            inputCostPer1M: '$0.10',
            outputCostPer1M: '$0.40',
            reasoningTrace: `[GEMINI FLASH LOW-LATENCY TRACE]
- Fast token decoding initialized.
- Using Go standard library context, time, and sync primitives.
- Optimized for instant TTFT (<180ms).`,
            output: `\`\`\`go
// Gemini 2.0 Flash High-Throughput Implementation
package main

import (
    "fmt"
    "time"
)

func main() {
    rateLimiter := time.Tick(100 * time.Millisecond)
    for i := 0; i < 5; i++ {
        <-rateLimiter
        go fmt.Printf("[%s] Task %d dispatched\\n", time.Now().Format("15:04:05.000"), i)
    }
    time.Sleep(1 * time.Second)
}
\`\`\``
          }
        };

        const respA = modelKnowledge[modelA] || modelKnowledge['claude-3-7-sonnet'];
        const respB = modelKnowledge[modelB] || modelKnowledge['gpt-o3-mini'];

        return sendJsonResponse(res, 200, {
          success: true,
          prompt,
          modelA: {
            id: modelA,
            ...respA,
            latencyMs: Math.round(150 + Math.random() * 80)
          },
          modelB: {
            id: modelB,
            ...respB,
            latencyMs: Math.round(200 + Math.random() * 120)
          },
          totalRoundtripMs: Date.now() - startTime
        });
      }

      // 13. Certificate Verification & Credential API
      if (pathname === '/api/v1/certificate/verify' && method === 'POST') {
        const body = await parseRequestBody(req);
        const studentName = body.studentName || 'Alex Rivera';
        const certId = body.certificateId || `NEXUS-AI-${Date.now().toString(36).toUpperCase()}`;

        // Compute simulated cryptographic SHA-256 signature stamp
        const verificationHash = '0x' + Array.from(studentName + certId + '2026-HONORS')
          .map(c => c.charCodeAt(0).toString(16).padStart(2, '0'))
          .join('')
          .padEnd(64, 'a')
          .slice(0, 64);

        return sendJsonResponse(res, 200, {
          success: true,
          verified: true,
          certificateId: certId,
          studentName,
          credentialTitle: 'Master of Generative AI Architecture, Vibe Coding & LLM Engineering',
          issuingInstitution: 'AI Nexus Academy & Research Labs',
          issuanceDate: new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }),
          verificationHash,
          curriculumCompleted: '17 Core Modules, 50+ Vibe Prompts, OWASP LLM Defense, REST Engine Deployment',
          status: 'OFFICIALLY_VERIFIED_CREDENTIAL',
          latencyMs: Date.now() - startTime
        });
      }

      // 14. Prompt Golf Evaluation API
      if (pathname === '/api/v1/golf/evaluate' && method === 'POST') {
        const body = await parseRequestBody(req);
        const prompt = (body.prompt || '').trim();
        const levelId = body.levelId || 'level_1';

        const levels = {
          level_1: { name: 'Clean JSON Extractor', par: 25, targetKey: 'JSON' },
          level_2: { name: 'SQL Safe Parameterizer', par: 35, targetKey: 'SQL' },
          level_3: { name: 'Prompt Injection Shield', par: 40, targetKey: 'XML' },
          level_4: { name: 'ELI5 Quantum Superposition', par: 30, targetKey: 'Quantum' }
        };

        const currentLvl = levels[levelId] || levels.level_1;
        const rawTokens = prompt.length > 0 ? Math.ceil(prompt.length / 3.8) : 0;
        const strokes = rawTokens;
        const diff = strokes - currentLvl.par;

        let rating = 'PAR';
        let xpAward = 50;
        let badge = '🎯 Par';

        if (strokes === 0) {
          rating = 'NO_INPUT';
          badge = '⚠️ Empty';
        } else if (diff <= -5) {
          rating = 'HOLE_IN_ONE';
          badge = '⛳ HOLE-IN-ONE!';
          xpAward = 250;
        } else if (diff <= -2) {
          rating = 'EAGLE';
          badge = '🦅 Eagle (-2)';
          xpAward = 180;
        } else if (diff < 0) {
          rating = 'BIRDIE';
          badge = '🐦 Birdie (-1)';
          xpAward = 120;
        } else if (diff === 0) {
          rating = 'PAR';
          badge = '🎯 Even Par';
          xpAward = 80;
        } else {
          rating = 'BOGEY';
          badge = `⛳ Bogey (+${diff})`;
          xpAward = 30;
        }

        return sendJsonResponse(res, 200, {
          success: true,
          level: currentLvl.name,
          par: currentLvl.par,
          tokensUsed: strokes,
          scoreDiff: diff > 0 ? `+${diff}` : `${diff}`,
          rating,
          badge,
          xpAward,
          feedback: diff <= 0 ? 'Outstanding token efficiency! Minimal prompt payload achieved maximum compliance.' : 'Prompt is compliant but exceeds target token par. Try removing redundant conversational filler.',
          latencyMs: Date.now() - startTime
        });
      }

      // 15. Neural Node Flow Pipeline Execution API
      if (pathname === '/api/v1/flow/execute' && method === 'POST') {
        const body = await parseRequestBody(req);
        const query = body.query || 'Explain how Transformers compute multi-head self-attention.';
        const activeNodes = body.nodes || ['input', 'embed', 'vector_db', 'guardrail', 'llm', 'validator'];

        const pipelineHops = [
          { node: 'User Query Ingestion', status: 'COMPLETE', latencyMs: 2, payload: query.slice(0, 45) + '...' },
          { node: 'text-embedding-3-small', status: 'COMPLETE', latencyMs: 18, payload: 'Vector [1536 floats, norm: 1.00]' },
          { node: 'Pinecone Vector DB (Top-K=3)', status: 'COMPLETE', latencyMs: 24, payload: 'Retrieved 3 chunks (Score: 0.912)' },
          { node: 'Llama-Guard 3 Injection Filter', status: 'SAFE_PASSED', latencyMs: 8, payload: 'Safety Score: 100/100 (Safe)' },
          { node: 'Claude 3.7 Sonnet Inference', status: 'STREAM_COMPLETE', latencyMs: 145, payload: 'Generated 280 tokens' },
          { node: 'JSON Schema Output Validator', status: 'PASSED', latencyMs: 3, payload: 'RFC-8259 Compliant JSON' }
        ];

        return sendJsonResponse(res, 200, {
          success: true,
          totalPipelineLatencyMs: 200,
          hopsCount: pipelineHops.length,
          pipelineHops,
          finalOutput: 'Multi-Head Attention projects Queries (Q), Keys (K), and Values (V) into h distinct representation subspaces using scaled dot-product: Softmax(QK^T / sqrt(d_k))V.',
          status: 'PIPELINE_EXECUTION_SUCCESS',
          latencyMs: Date.now() - startTime
        });
      }

      // 16. Autonomous Multi-Agent Swarm Mission API
      if (pathname === '/api/v1/swarm/run' && method === 'POST') {
        const body = await parseRequestBody(req);
        const mission = body.mission || 'Build an async FastAPI microservice with Stripe webhook and Redis rate-limiter.';

        const swarmDialog = [
          {
            agent: 'Architect (Claude 3.7 Opus)',
            role: 'System Design & Blueprinting',
            color: '#0284c7',
            message: `Initiating mission architecture for: "${mission}". Breaking into 3 sub-tasks: 1) Data model specification, 2) Async handler with Redis token-bucket, 3) Stripe webhook idempotency.`
          },
          {
            agent: 'Full-Stack Coder (Claude 3.7 Sonnet)',
            role: 'Production Implementation',
            color: '#7c3aed',
            message: `Architecture accepted. Implementing FastAPI router with Pydantic v2 schemas and redis.asyncio connection pool. Generated 142 lines of clean async Python code.`
          },
          {
            agent: 'Security Auditor (OpenAI o3-mini)',
            role: 'OWASP & Vulnerability Analysis',
            color: '#d97706',
            message: `Auditing code: Verified Stripe signature verification using stripe.Webhook.construct_event(). Verified zero hardcoded secrets. Added Redis rate limiter fallback. Status: APPROVED FOR DEPLOYMENT.`
          }
        ];

        return sendJsonResponse(res, 200, {
          success: true,
          mission,
          swarmAgentsCount: 3,
          dialogCount: swarmDialog.length,
          swarmDialog,
          finalArtifact: 'production_microservice.py (Verified & Approved)',
          status: 'MISSION_ACCOMPLISHED',
          latencyMs: Date.now() - startTime
        });
      }

      // 404 for unknown API routes
      return sendJsonResponse(res, 404, {
        error: `Endpoint '${pathname}' not found. Available endpoints: /api/v1/health, /api/v1/courses, /api/v1/vibe/generate, /api/v1/prompt/optimize, /api/v1/tokens/tokenize, /api/v1/rag/simulate, /api/v1/tutor/explain, /api/v1/security/audit, /api/v1/frontend/component, /api/v1/backend/microservice, /api/v1/uiux/wireframe, /api/v1/arena/compare, /api/v1/certificate/verify, /api/v1/golf/evaluate, /api/v1/flow/execute, /api/v1/swarm/run`
      });

    } catch (err) {
      return sendJsonResponse(res, 500, {
        error: 'Internal Server API Error',
        message: err.message
      });
    }
  }

  // =========================================================================
  // STATIC FILE SERVING
  // =========================================================================
  let reqUrl = pathname === '/' ? 'index.html' : pathname.replace(/^\//, '');
  let filePath = path.join(__dirname, reqUrl);

  const extname = String(path.extname(filePath)).toLowerCase();
  const contentType = MIME_TYPES[extname] || 'application/octet-stream';

  fs.readFile(filePath, (error, content) => {
    if (error) {
      if (error.code === 'ENOENT') {
        res.writeHead(404, { 'Content-Type': 'text/html' });
        res.end('<h1 style="font-family:sans-serif; text-align:center; margin-top:50px;">404 - Page Not Found</h1>', 'utf-8');
      } else {
        res.writeHead(500);
        res.end(`Server Error: ${error.code}`);
      }
    } else {
      res.writeHead(200, { 
        'Content-Type': contentType,
        'X-Content-Type-Options': 'nosniff',
        'X-Frame-Options': 'SAMEORIGIN',
        'X-XSS-Protection': '1; mode=block',
        'Referrer-Policy': 'strict-origin-when-cross-origin',
        'Cache-Control': 'no-cache'
      });
      res.end(content, 'utf-8');
    }
  });
});

server.listen(PORT, () => {
  console.log(`🚀 AI Nexus Academy Full-Stack Server & REST API is running at http://localhost:${PORT}`);
  console.log(`📡 API Endpoints available under http://localhost:${PORT}/api/v1/...`);
});
